version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE_HOST: mysql
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE_USER: user
      MYSQL_DATABASE_PASSWORD: password
      MYSQL_DATABASE_DB: bookdb

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      BACKEND_API_URL: http://backend:5001

volumes:
  mysql_data:
