version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_BACKEND_URL=http://backend:5001
    depends_on:
      - backend
      - mysql

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      MYSQL_DATABASE_HOST: "mysql"
      MYSQL_DATABASE_PORT: "3306"
      MYSQL_DATABASE_USER: "tf_rds_user1"
      MYSQL_DATABASE_PASSWORD: "password"  # Set your password here
      MYSQL_DATABASE_DB: "bookdb"
      USE_LOCAL_DB: "true"
      AWS_REGION: "us-east-1"
      DB_MASTER_USER: "root"
      DB_MASTER_PASSWORD: "rootpassword"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  test:
    build:
      context: ./tests
      dockerfile: Dockerfile.test
    depends_on:
      - frontend
      - backend
      - mysql

volumes:
  mysql-data:
